"""
Export the Excel Model of Record.

Reads exclusively from 02_processed_data/*.csv (generated by
04_streamlit_app/refresh_data.py) plus the static, checked-in
01_raw_data/scheme_master/*.csv config files, and writes a single audit
workbook:

    03_excel_model/MF_Risk_Diagnostic_Model.xlsx

This script performs NO calculations of its own beyond simple re-selection,
pivoting, and grouping of already-computed processed columns (e.g. the
Memo Inputs sheet). It never invents a number, never writes a live Excel
formula, and never hardcodes a financial figure — every cell traces back to
a specific 02_processed_data/*.csv (or 01_raw_data/scheme_master/*.csv)
column. This workbook is a model-of-record *export* for auditability, not a
calculation engine; the calculation engines are the src/*.py modules.

Run manually after refresh_data.py:

    python 04_streamlit_app/export_excel_model.py

Reference: 00_project_control/master_project_instructions.md.md §24
(Excel Model of Record).
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

_THIS_FILE = Path(__file__).resolve()
_SRC_DIR = _THIS_FILE.parent / "src"
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))

import data_loader as dl  # noqa: E402
from benchmarks import MIN_ALIGNED_OBSERVATIONS_FOR_STATIC_METRICS, ROLLING_WINDOW_DAYS  # noqa: E402
from data_cleaning import SUSPICIOUS_RETURN_THRESHOLD  # noqa: E402
from returns import PROJECT_ROOT  # noqa: E402
from stress import DEFAULT_BASE_PORTFOLIO_VALUE  # noqa: E402
from utils import (  # noqa: E402
    CACHE_MAX_AGE_HOURS,
    CLIENT_PROFILES,
    DATA_START_DATE,
    DEFAULT_RISK_FREE_RATE,
    MONTHS_PER_YEAR,
    REQUIRED_BENCHMARKS,
    TRADING_DAYS_PER_YEAR,
    is_dataframe_usable,
)

EXPORT_TIMESTAMP = datetime.now()
EXPORT_TIMESTAMP_STR = EXPORT_TIMESTAMP.strftime("%Y-%m-%d %H:%M:%S")

SCHEME_MASTER_DIR = PROJECT_ROOT / "01_raw_data" / "scheme_master"
FUND_MASTER_PATH = SCHEME_MASTER_DIR / "fund_master.csv"
BENCHMARK_MAP_PATH = SCHEME_MASTER_DIR / "benchmark_map.csv"
PORTFOLIO_WEIGHTS_PATH = SCHEME_MASTER_DIR / "portfolio_weights.csv"
STRESS_SCENARIOS_PATH = SCHEME_MASTER_DIR / "stress_scenarios.csv"

EXCEL_MODEL_DIR = PROJECT_ROOT / "03_excel_model"
EXCEL_MODEL_PATH = EXCEL_MODEL_DIR / "MF_Risk_Diagnostic_Model.xlsx"

LAST_REFRESHED_NOTE = (
    f"Last refreshed: {EXPORT_TIMESTAMP_STR} (generated by 04_streamlit_app/export_excel_model.py — "
    "no manual edits; re-run the script after refresh_data.py to update)."
)
NO_DATA_NOTE = (
    "NO DATA AVAILABLE - the source processed CSV does not exist yet. Run "
    "python 04_streamlit_app/refresh_data.py to generate it, then re-run this export."
)

# Documented sheet order, 00 first (see master_project_instructions.md.md §24 / this task's spec).
SHEET_ORDER_AFTER_CONTROL = [
    "01_Assumptions", "02_Fund_Master", "03_Benchmark_Map", "04_NAV_Daily_Clean", "05_Data_QA",
    "06_Returns_Daily", "07_NAV_Monthly", "08_Returns_Monthly", "09_Rolling_Metrics",
    "10_Benchmark_Relative", "11_Metrics", "12_Stress_Results", "13_Stress_Attribution",
    "14_Suitability", "15_Memo_Inputs",
]
CONTROL_SHEET_NAME = "00_Model_Control"
FULL_SHEET_ORDER = [CONTROL_SHEET_NAME] + SHEET_ORDER_AFTER_CONTROL

TITLE_FONT = Font(bold=True, size=14, color="1F4E78")
SUBTITLE_FONT = Font(italic=True, size=10, color="595959")
SECTION_FONT = Font(bold=True, size=11, color="1F4E78")
MISSING_FONT = Font(italic=True, bold=True, color="C00000")
HEADER_FONT = Font(bold=True, color="FFFFFF")
HEADER_FILL = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
MAX_COLUMN_WIDTH = 60
MIN_COLUMN_WIDTH = 10


# ---------------------------------------------------------------------------
# Static config readers (never a live fetch — 01_raw_data/scheme_master/ is
# checked-in reference config, not fetched/cached API data)
# ---------------------------------------------------------------------------

def _read_config_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


# ---------------------------------------------------------------------------
# Low-level formatting helpers
# ---------------------------------------------------------------------------

def _style_header_row(ws: Worksheet, header_row: int, n_columns: int) -> None:
    for col_idx in range(1, n_columns + 1):
        cell = ws.cell(row=header_row, column=col_idx)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)


def _autosize_columns(ws: Worksheet, df: pd.DataFrame, start_col: int = 1) -> None:
    for offset, column in enumerate(df.columns):
        col_idx = start_col + offset
        try:
            content_width = int(df[column].astype(str).map(len).max()) if len(df) else 0
        except Exception:  # noqa: BLE001 - width estimation must never break the export
            content_width = 0
        header_width = len(str(column))
        width = max(MIN_COLUMN_WIDTH, min(MAX_COLUMN_WIDTH, max(content_width, header_width) + 2))
        ws.column_dimensions[get_column_letter(col_idx)].width = width


def _apply_date_format(ws: Worksheet, df: pd.DataFrame, header_row: int, date_columns: List[str]) -> None:
    n_rows = len(df)
    if n_rows == 0:
        return
    for column in date_columns:
        if column not in df.columns:
            continue
        col_idx = list(df.columns).index(column) + 1
        for row in ws.iter_rows(min_row=header_row + 1, max_row=header_row + n_rows, min_col=col_idx, max_col=col_idx):
            row[0].number_format = "yyyy-mm-dd"


def _write_meta_block(ws: Worksheet, title: str, source_note: str, extra_notes: Optional[List[str]] = None) -> int:
    """Write the title / source-note / extra-notes / last-refreshed block starting at row 1.
    Returns the 1-indexed row number of the blank separator row immediately below the block
    (i.e. the row the data table's header should occupy is this value + 1)."""
    row = 1
    ws.cell(row=row, column=1, value=title).font = TITLE_FONT
    row += 1
    ws.cell(row=row, column=1, value=f"Data source: {source_note}").font = SUBTITLE_FONT
    row += 1
    for note in extra_notes or []:
        ws.cell(row=row, column=1, value=note).font = SUBTITLE_FONT
        row += 1
    ws.cell(row=row, column=1, value=LAST_REFRESHED_NOTE).font = SUBTITLE_FONT
    row += 1
    return row


def _write_data_table(
    ws: Worksheet, df: pd.DataFrame, header_row: int, date_columns: Optional[List[str]] = None
) -> int:
    """Write a DataFrame's header + rows directly via openpyxl cell writes (used for the two
    hand-composed sheets: 00_Model_Control and 10_Benchmark_Relative). Returns the next free row."""
    has_data = is_dataframe_usable(df)
    df_to_write = df if has_data else pd.DataFrame(columns=list(df.columns) if df is not None else [])

    for col_idx, column in enumerate(df_to_write.columns, start=1):
        ws.cell(row=header_row, column=col_idx, value=str(column))
    for row_offset, record in enumerate(df_to_write.itertuples(index=False, name=None), start=1):
        for col_idx, value in enumerate(record, start=1):
            ws.cell(row=header_row + row_offset, column=col_idx, value=value)

    if len(df_to_write.columns) > 0:
        _style_header_row(ws, header_row=header_row, n_columns=len(df_to_write.columns))
        _autosize_columns(ws, df_to_write)
        if date_columns:
            _apply_date_format(ws, df_to_write, header_row=header_row, date_columns=date_columns)

    if not has_data:
        ws.cell(row=header_row + 1, column=1, value=NO_DATA_NOTE).font = MISSING_FONT
        return header_row + 2
    return header_row + len(df_to_write) + 1


def _write_table_sheet(
    writer: "pd.ExcelWriter",
    sheet_name: str,
    title: str,
    source_note: str,
    df: pd.DataFrame,
    extra_notes: Optional[List[str]] = None,
    date_columns: Optional[List[str]] = None,
) -> Worksheet:
    """
    Write one processed dataset to its own sheet with a title / data-source /
    last-refreshed meta block above a styled, auto-sized data table (bulk
    written via pandas.to_excel for speed on the larger datasets). Gracefully
    degrades (still produces a valid, clearly-labelled sheet) if the source
    dataset is missing or empty.
    """
    has_data = is_dataframe_usable(df)
    df_to_write = df if has_data else pd.DataFrame(columns=list(df.columns) if df is not None else [])

    meta_line_count = 3 + len(extra_notes or [])  # title + source note + extra notes + last-refreshed
    header_row_0idx = meta_line_count  # to_excel startrow is 0-indexed; this leaves exactly one blank row above
    df_to_write.to_excel(writer, sheet_name=sheet_name, index=False, startrow=header_row_0idx)
    ws = writer.sheets[sheet_name]

    _write_meta_block(ws, title=title, source_note=source_note, extra_notes=extra_notes)
    header_row = header_row_0idx + 1
    if not has_data:
        ws.cell(row=header_row + 1, column=1, value=NO_DATA_NOTE).font = MISSING_FONT

    if len(df_to_write.columns) > 0:
        _style_header_row(ws, header_row=header_row, n_columns=len(df_to_write.columns))
        _autosize_columns(ws, df_to_write)
        if date_columns:
            _apply_date_format(ws, df_to_write, header_row=header_row, date_columns=date_columns)
        ws.freeze_panes = ws.cell(row=header_row + 1, column=1).coordinate
    return ws


def _append_table_block(
    ws: Worksheet, start_row: int, section_title: str, df: pd.DataFrame, date_columns: Optional[List[str]] = None
) -> int:
    """Append a secondary titled table further down an already-open sheet (used by
    10_Benchmark_Relative to show static full-history metrics and rolling 252D metrics on one
    sheet). Returns the next free row after the appended block plus one blank padding row."""
    ws.cell(row=start_row, column=1, value=section_title).font = SECTION_FONT
    header_row = start_row + 1
    next_row = _write_data_table(ws, df, header_row=header_row, date_columns=date_columns)
    return next_row + 1


# ---------------------------------------------------------------------------
# 15_Memo_Inputs — derived, re-selected/pivoted view only (no new figures)
# ---------------------------------------------------------------------------

def _build_memo_inputs(
    fund_master: pd.DataFrame,
    metrics_summary: pd.DataFrame,
    stress_results: pd.DataFrame,
    attribution_results: pd.DataFrame,
    suitability_results: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build a one-row-per-fund "talking points" sheet for writing the Notion
    methodology note / LinkedIn carousel without re-deriving figures by
    hand. Every column here is a direct re-selection, groupby, or pivot of
    an existing processed-data column — nothing is recomputed or estimated.
    """
    empty_columns = [
        "fund_label", "category", "sleeve", "primary_benchmark", "cagr", "annualized_volatility",
        "sharpe_ratio", "max_drawdown", "daily_cvar_95", "recovery_period_days",
        "worst_stress_scenario", "worst_stress_loss", "largest_loss_contributor_scenario_count",
        "role_conservative", "role_balanced", "role_growth", "role_aggressive",
    ]
    if not is_dataframe_usable(metrics_summary):
        return pd.DataFrame(columns=empty_columns)

    base_columns = [
        "fund_label", "cagr", "annualized_volatility", "sharpe_ratio", "max_drawdown", "daily_cvar_95",
        "recovery_period_days",
    ]
    memo_df = metrics_summary[base_columns].copy()

    if is_dataframe_usable(fund_master):
        fund_lookup = fund_master[["fund_label", "category", "sleeve", "primary_benchmark"]].drop_duplicates(
            "fund_label"
        )
        memo_df = memo_df.merge(fund_lookup, on="fund_label", how="left")

    if is_dataframe_usable(stress_results):
        worst_per_fund = (
            stress_results.sort_values("stress_return")
            .groupby("fund_label", as_index=False)
            .first()[["fund_label", "scenario_name", "stress_return"]]
            .rename(columns={"scenario_name": "worst_stress_scenario", "stress_return": "worst_stress_loss"})
        )
        memo_df = memo_df.merge(worst_per_fund, on="fund_label", how="left")

    if is_dataframe_usable(attribution_results) and "is_largest_loss_contributor" in attribution_results.columns:
        is_largest = attribution_results["is_largest_loss_contributor"].fillna(False).astype(bool)
        contributor_counts = (
            attribution_results.loc[is_largest]
            .groupby("fund_label")
            .size()
            .rename("largest_loss_contributor_scenario_count")
            .reset_index()
        )
        memo_df = memo_df.merge(contributor_counts, on="fund_label", how="left")
        memo_df["largest_loss_contributor_scenario_count"] = (
            memo_df["largest_loss_contributor_scenario_count"].fillna(0).astype(int)
        )

    if is_dataframe_usable(suitability_results):
        role_pivot = suitability_results.pivot_table(
            index="fund_label", columns="client_profile", values="suitability_role", aggfunc="first"
        )
        role_pivot.columns = [f"role_{str(profile).lower()}" for profile in role_pivot.columns]
        role_pivot = role_pivot.reindex(columns=[f"role_{profile.lower()}" for profile in CLIENT_PROFILES])
        memo_df = memo_df.merge(role_pivot.reset_index(), on="fund_label", how="left")

    return memo_df


# ---------------------------------------------------------------------------
# Main export
# ---------------------------------------------------------------------------

def build_workbook() -> None:
    """Load every processed dataset once, then write all sheets in the documented order."""
    print("=" * 70)
    print("MF Risk Diagnostic Module - Excel Model of Record Export")
    print("=" * 70)

    fund_master = _read_config_csv(FUND_MASTER_PATH)
    benchmark_map = _read_config_csv(BENCHMARK_MAP_PATH)

    nav_daily = dl.load_nav_daily()
    data_quality_report = dl.load_data_quality_report()
    returns_daily = dl.load_returns_daily()
    nav_monthly = dl.load_nav_monthly()
    returns_monthly = dl.load_returns_monthly()
    rolling_metrics = dl.load_rolling_metrics()
    benchmark_metrics = dl.load_benchmark_metrics()
    rolling_benchmark_metrics = dl.load_rolling_benchmark_metrics()
    metrics_summary = dl.load_metrics_summary()
    stress_results = dl.load_stress_results()
    attribution_results = dl.load_attribution_results()
    suitability_results = dl.load_suitability_results()

    memo_inputs = _build_memo_inputs(
        fund_master, metrics_summary, stress_results, attribution_results, suitability_results
    )

    assumptions_df = pd.DataFrame(
        [
            ("Default risk-free rate", f"{DEFAULT_RISK_FREE_RATE:.2%}",
             "utils.DEFAULT_RISK_FREE_RATE - used in Sharpe/Sortino/rolling Sharpe; overridable, always disclosed."),
            ("Trading days per year", TRADING_DAYS_PER_YEAR,
             "utils.TRADING_DAYS_PER_YEAR - daily-to-annual volatility/tracking-error annualization (x SQRT(252))."),
            ("Months per year", MONTHS_PER_YEAR,
             "utils.MONTHS_PER_YEAR - monthly-to-annual annualization (x SQRT(12))."),
            ("Data horizon floor", DATA_START_DATE,
             "utils.DATA_START_DATE - no observation before this date is used in any calculation."),
            ("API cache freshness TTL", f"{CACHE_MAX_AGE_HOURS} hours",
             "utils.CACHE_MAX_AGE_HOURS - cached API responses older than this are refetched."),
            ("Default base portfolio value", f"INR {DEFAULT_BASE_PORTFOLIO_VALUE:,.0f}",
             "stress.DEFAULT_BASE_PORTFOLIO_VALUE - used for stress Loss Amount (INR) and Post-Stress Portfolio Value."),
            ("Suspicious daily return threshold", f"+/- {SUSPICIOUS_RETURN_THRESHOLD:.0%}",
             "data_cleaning.SUSPICIOUS_RETURN_THRESHOLD - flagged (not removed) in data_quality_report.csv."),
            ("Min. aligned observations for static benchmark-relative metrics", MIN_ALIGNED_OBSERVATIONS_FOR_STATIC_METRICS,
             "benchmarks.MIN_ALIGNED_OBSERVATIONS_FOR_STATIC_METRICS - below this, beta/TE/IR/capture are NaN."),
            ("Rolling benchmark-relative window", f"{ROLLING_WINDOW_DAYS} trading days",
             "benchmarks.ROLLING_WINDOW_DAYS - rolling beta / tracking error / information ratio window."),
            ("Required benchmark series", ", ".join(REQUIRED_BENCHMARKS), "utils.REQUIRED_BENCHMARKS"),
            ("Client profiles modeled", ", ".join(CLIENT_PROFILES),
             "utils.CLIENT_PROFILES - suitability_results.csv produces one row per (fund, profile) pair."),
        ],
        columns=["Assumption", "Value", "Source constant / note"],
    )

    EXCEL_MODEL_DIR.mkdir(parents=True, exist_ok=True)

    sheet_specs: List[Dict] = [
        {"name": "02_Fund_Master", "desc": "Fund universe configuration (5 sleeves, scheme codes, verification status).",
         "source": "01_raw_data/scheme_master/fund_master.csv (static config, not fetched)", "df": fund_master},
        {"name": "03_Benchmark_Map", "desc": "Primary/secondary benchmark assignment per fund.",
         "source": "01_raw_data/scheme_master/benchmark_map.csv (static config, not fetched)", "df": benchmark_map},
        {"name": "04_NAV_Daily_Clean", "desc": "Validated, deduplicated, 2021-01-01+ daily NAV per fund.",
         "source": "02_processed_data/nav_daily_clean.csv", "df": nav_daily, "date_cols": ["date"]},
        {"name": "05_Data_QA", "desc": "Data quality/completeness/plausibility audit per fund & benchmark.",
         "source": "02_processed_data/data_quality_report.csv", "df": data_quality_report,
         "date_cols": ["first_date", "last_date"]},
        {"name": "06_Returns_Daily", "desc": "Daily fund returns (NAV-to-NAV, within-fund only).",
         "source": "02_processed_data/returns_daily.csv", "df": returns_daily, "date_cols": ["date"]},
        {"name": "07_NAV_Monthly", "desc": "Month-end NAV per fund (latest observation in each calendar month).",
         "source": "02_processed_data/nav_monthly.csv", "df": nav_monthly, "date_cols": ["month_end_date"]},
        {"name": "08_Returns_Monthly", "desc": "Month-end-to-month-end fund returns.",
         "source": "02_processed_data/returns_monthly.csv", "df": returns_monthly, "date_cols": ["month_end_date"]},
        {"name": "09_Rolling_Metrics",
         "desc": "Long-form rolling returns/volatility/Sharpe (3/6/12/24/36M returns; 63/126/252D vol; 252D Sharpe).",
         "source": "02_processed_data/rolling_metrics.csv", "df": rolling_metrics, "date_cols": ["date_or_month"]},
        {"name": "11_Metrics",
         "desc": "Full-history fund-level risk/return metrics (CAGR, volatility, Sharpe, Sortino, drawdown, VaR/CVaR, ...).",
         "source": "02_processed_data/metrics_summary.csv", "df": metrics_summary,
         "date_cols": ["data_start_date", "data_end_date", "as_of_date"]},
        {"name": "12_Stress_Results", "desc": "Historical-replay and deterministic stress scenario returns per fund.",
         "source": "02_processed_data/stress_results.csv", "df": stress_results,
         "date_cols": ["window_start", "window_end"]},
        {"name": "13_Stress_Attribution",
         "desc": "Fund loss contribution, stress loss share vs. portfolio weight, INR loss amounts.",
         "source": "02_processed_data/attribution_results.csv", "df": attribution_results},
        {"name": "14_Suitability",
         "desc": "Educational suitability diagnostics: role/action/risk-warning per (fund, client profile).",
         "source": "02_processed_data/suitability_results.csv", "df": suitability_results},
    ]

    control_rows: List[Tuple] = []

    with pd.ExcelWriter(EXCEL_MODEL_PATH, engine="openpyxl") as writer:
        # --- 01_Assumptions ---
        _write_table_sheet(
            writer,
            "01_Assumptions",
            title="01. Assumptions",
            source_note="Constants defined in 04_streamlit_app/src/{utils,stress,benchmarks,data_cleaning}.py",
            df=assumptions_df,
            extra_notes=["Every assumption below is a named Python constant, never a hardcoded value re-typed in Excel."],
        )
        control_rows.append(("01_Assumptions", "Model assumptions & default parameters", "src/*.py constants", len(assumptions_df), "OK"))

        # --- 02 through 09, 11 through 14: one processed dataset per sheet ---
        for spec in sheet_specs:
            _write_table_sheet(
                writer,
                spec["name"],
                title=f"{spec['name'].split('_', 1)[0]}. {spec['name'].split('_', 1)[1].replace('_', ' ')}",
                source_note=spec["source"],
                df=spec["df"],
                date_columns=spec.get("date_cols"),
            )
            row_count = len(spec["df"]) if is_dataframe_usable(spec["df"]) else 0
            status = "OK" if is_dataframe_usable(spec["df"]) else "NO DATA - run refresh_data.py"
            control_rows.append((spec["name"], spec["desc"], spec["source"], row_count, status))

        # --- 10_Benchmark_Relative: static + rolling benchmark-relative metrics on one sheet ---
        bench_source = "02_processed_data/benchmark_metrics.csv + 02_processed_data/rolling_benchmark_metrics.csv"
        ws_bench = writer.book.create_sheet("10_Benchmark_Relative")
        next_row = _write_meta_block(
            ws_bench,
            title="10. Benchmark Relative",
            source_note=bench_source,
            extra_notes=["Each fund is matched only to its own primary_benchmark per benchmark_map.csv."],
        ) + 1
        next_row = _append_table_block(
            ws_bench, next_row, "Static, full-history metrics (benchmark_metrics.csv)", benchmark_metrics
        )
        _append_table_block(
            ws_bench,
            next_row,
            f"Rolling {ROLLING_WINDOW_DAYS}-trading-day metrics (rolling_benchmark_metrics.csv)",
            rolling_benchmark_metrics,
            date_columns=["date"],
        )
        ws_bench.freeze_panes = None
        bench_rows = (len(benchmark_metrics) if is_dataframe_usable(benchmark_metrics) else 0) + (
            len(rolling_benchmark_metrics) if is_dataframe_usable(rolling_benchmark_metrics) else 0
        )
        bench_status = "OK" if bench_rows > 0 else "NO DATA - run refresh_data.py"
        control_rows.append((
            "10_Benchmark_Relative",
            "Beta, tracking error, information ratio, capture ratios (static + rolling).",
            bench_source, bench_rows, bench_status,
        ))

        # --- 15_Memo_Inputs ---
        _write_table_sheet(
            writer,
            "15_Memo_Inputs",
            title="15. Memo Inputs",
            source_note=(
                "Derived re-selection/pivot of 02_processed_data/{metrics_summary,stress_results,"
                "attribution_results,suitability_results}.csv + 01_raw_data/scheme_master/fund_master.csv"
            ),
            df=memo_inputs,
            extra_notes=[
                "Convenience 'one row per fund' cheat sheet for writing the Notion methodology note / "
                "LinkedIn carousel copy without manually re-deriving figures. No new numbers are computed "
                "here - every column is a direct groupby/pivot/merge of an existing processed-data column."
            ],
        )
        control_rows.append((
            "15_Memo_Inputs", "Derived per-fund talking-points summary for external memos/carousel copy.",
            "Multiple processed CSVs (re-selected/pivoted only)", len(memo_inputs),
            "OK" if is_dataframe_usable(memo_inputs) else "NO DATA - run refresh_data.py",
        ))

        # --- 00_Model_Control: written last (needs every row count above), placed first below ---
        control_df = pd.DataFrame(control_rows, columns=["Sheet", "Contents", "Source File(s)", "Row Count", "Status"])
        control_df["_order"] = control_df["Sheet"].map({name: idx for idx, name in enumerate(SHEET_ORDER_AFTER_CONTROL)})
        control_df = control_df.sort_values("_order").drop(columns="_order").reset_index(drop=True)

        ws_control = writer.book.create_sheet(CONTROL_SHEET_NAME)
        control_next_row = _write_meta_block(
            ws_control,
            title="00. Model Control",
            source_note="Generated from every other sheet in this workbook by export_excel_model.py.",
            extra_notes=[
                "This workbook is a read-only audit export from 02_processed_data/ + "
                "01_raw_data/scheme_master/. It contains no manually entered figures and no live Excel "
                "formulas referencing external data. To refresh: run "
                "'python 04_streamlit_app/refresh_data.py' then 'python 04_streamlit_app/export_excel_model.py'.",
            ],
        ) + 1
        _write_data_table(ws_control, control_df, header_row=control_next_row)
        ws_control.freeze_panes = ws_control.cell(row=control_next_row + 1, column=1).coordinate

        # --- Enforce final sheet order (00 first, 01-15 as documented) and drop any stray default sheet ---
        writer.book._sheets = [writer.book[name] for name in FULL_SHEET_ORDER if name in writer.book.sheetnames]
        for ws in writer.book.worksheets:
            ws.sheet_view.showGridLines = False

    print(f"\nWorkbook written to: {EXCEL_MODEL_PATH}")
    print(f"Sheets: {len(FULL_SHEET_ORDER)}")
    for sheet_name, _desc, _source, row_count, status in control_rows:
        marker = "[OK]  " if status == "OK" else "[WARN]"
        print(f"  {marker} {sheet_name:<24} rows={row_count:<8} {status}")
    print("=" * 70)


def main() -> None:
    try:
        build_workbook()
    except Exception as exc:  # noqa: BLE001 - surface a clear top-level failure message
        print(f"\nEXPORT FAILED: {type(exc).__name__}: {exc}")
        raise


if __name__ == "__main__":
    main()
